version: '3'

services:

  mosquitto_module:
    image: eclipse-mosquitto:latest
    container_name: se4as-mosquitto_module
    hostname: mosquitto_module
    volumes:
      - ./CrossRoad/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - TZ=Europe/Rome


  monitor_module:
    image: se4as/monitor
    build: CrossRoad/Monitor
    container_name: se4as-monitor_module
    hostname: monitor_module
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - TZ=Europe/Rome
    depends_on:
      - mosquitto_module
      - configuration_module
      - analyzer_module
      - seas_influxdb

  analyzer_module:
    image: se4as/analyzer
    build: CrossRoad/Analyzer
    container_name: se4as-analyzer_module
    hostname: analyzer_module
    ports:
      - "8090:8080"
    expose:
      - 8090
    environment:
      - TZ=Europe/Rome
    depends_on:
      - mosquitto_module
      - configuration_module
      - planner1_module
      - seas_influxdb

  analyzer_switcher_module:
    image: se4as/analyzer_switcher
    build: TrafficSwitcher/Analyzer_Switcher
    container_name: se4as-analyzer_module_switcher
    hostname: analyzer_module2
    ports:
      - "8150:8080"
    expose:
      - 8150
    environment:
      - TZ=Europe/Rome
    depends_on:
      - mosquitto_module
      - configuration_module_switcher
      - planner_switcher_module
      - seas_influxdb

  planner1_module:
    image: se4as/planner1
    build: CrossRoad/Planner_1
    container_name: se4as-planner1_module
    hostname: planner1_module
    ports:
      - "8100:8080"
    expose:
      - 8100
    environment:
      - TZ=Europe/Rome
    depends_on:
      - mosquitto_module
      - configuration_module
      - executor
      - seas_influxdb

  planner_switcher_module:
    image: se4as/planner_switcher
    build: TrafficSwitcher/Planner_Switcher
    container_name: se4as-planner_switcher_module
    hostname: planner2_module
    ports:
      - "8110:8080"
    expose:
      - 8110
    environment:
      - TZ=Europe/Rome
    depends_on:
      - mosquitto_module
      - configuration_module_switcher
      - seas_influxdb

  executor:
    image: se4as/executor
    build: CrossRoad/Executor
    container_name: se4as-executor_module
    hostname: executor_module
    ports:
      - "8120:8080"
    expose:
      - 8120
    depends_on:
      - mosquitto_module
      - configuration_module
      - seas_influxdb

  managed_resources:
    image: se4as/managed_resources
    build: CrossRoad/Managed_resources
    container_name: se4as-managed_resources_module
    hostname: managed_resources_module
    ports:
      - "8130:8080"
    expose:
      - 8130
    depends_on:
      - seas_influxdb
      - mosquitto_module
      - configuration_module
      - monitor_module

  configuration_module:
    image: se4as/configuration_module
    build: CrossRoad/Configuration
    container_name: se4as-configuration_module
    hostname: configuration_module
    ports:
      - "8140:5008"
    expose:
      - 8140
    depends_on:
      - mosquitto_module


  configuration_module_switcher:
    image: se4as/configuration_module_switcher
    build: TrafficSwitcher/Configuration_Switcher
    container_name: se4as-configuration_module_switcher
    hostname: configuration_module2
    ports:
      - "8160:5008"
    expose:
      - 8160
    depends_on:
      - mosquitto_module

  seas_influxdb:
    image: influxdb:latest
    container_name: se4as-knowledge
    hostname: knowledge_module
    restart: always
    environment:
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=seas
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=seasinfluxdbtoken
    ports:
      - '8086:8086'
    expose:
      - 8086
    depends_on:
      - mosquitto_module

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana_module
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_ROOT_URL=http://172.20.0.104:3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - seas_influxdb